#!/bin/sh

# load nodejs env
. /home/deployer/.profile

read oldrev newrev refname
BRANCH=${refname#refs/heads/}
if [ "$BRANCH" != "master" ]; then
  echo "You're not pushing from master so it won't deploy."
  exit 0
fi

unset GIT_INDEX_FILE
export GIT_WORK_TREE=/home/deployer/apps/meiya-node
export GIT_DIR=/home/deployer/gitrepos/meiya.git

# fetch the code
git checkout -f

# npm install
cd $GIT_WORK_TREE
npm install --production

# copy processes.json if needed
if [ ! -f "$HOME/processes.json" ]; then
  cp $GIT_WORK_TREE/processes.json $HOME
fi

# start/restart meiya
pm2 startOrRestart $HOME/processes.json
#pm2 reload all
