#!/bin/sh

# load nodejs env
. /home/%USER%/.profile

read oldrev newrev refname
BRANCH=${refname#refs/heads/}
if [ "$BRANCH" != "master" ]; then
  echo "You're not pushing from master so it won't deploy."
  exit 0
fi

unset GIT_INDEX_FILE
export GIT_WORK_TREE=/home/%USER%/%APP_PATH%
export GIT_DIR=/home/%USER%/gitrepos/%APP_NAME%.git

# fetch the code
git checkout -f

# npm install
cd $GIT_WORK_TREE
npm install --production

# copy processes.json if needed
if [ ! -f "$HOME/processes-%APP_NAME%.json" ]; then
  cp $GIT_WORK_TREE/processes-%APP_NAME%.json $HOME
fi

# start/restart %APP_NAME%
pm2 startOrRestart $HOME/processes-%APP_NAME%.json
#pm2 reload all
